CREATE TABLE SELLER
(
  ID int  NOT NULL AUTO_INCREMENT,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  NAME VARCHAR(256) NOT NULL,
  STREET_ADDRESS    varchar(256) NOT NULL,
  STREET_ADDRESS2   varchar(256),
  CITY              varchar(256) NOT NULL,
  STATE             varchar(256) NOT NULL,
  ZIPCODE           varchar(20) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (EMAIL)
);

CREATE TABLE BUYER
(
  ID int  NOT NULL AUTO_INCREMENT,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  NAME VARCHAR(100)  NOT NULL, 
  EMAIL VARCHAR(256) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (EMAIL)
);

CREATE TABLE PROJECT
(
  ID int  NOT NULL AUTO_INCREMENT,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DESCRIPTION VARCHAR(256) NOT NULL,
  BID_DEADLINE DATETIME NOT NULL,
  MAX_BUDGET DECIMAL NOT NULL,
  SELLER_ID    int,
  FOREIGN KEY (SELLER_ID) REFERENCES SELLER(ID),
  PRIMARY KEY (ID)
);

CREATE TABLE BID
(
  ID int  NOT NULL AUTO_INCREMENT, 
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  BID_PRICE DECIMAL NOT NULL,
  BUYER_ID    int,
  FOREIGN KEY (BUYER_ID) REFERENCES BUYER(ID),
  PROJECT_ID    int,
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
  PRIMARY KEY (ID)
);

















